# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kartikeygupta/Workspace/nes-emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kartikeygupta/Workspace/nes-emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kartikeygupta/Workspace/nes-emulator/CMakeFiles /Users/kartikeygupta/Workspace/nes-emulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kartikeygupta/Workspace/nes-emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nesemu

# Build rule for target.
nesemu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nesemu
.PHONY : nesemu

# fast build rule for target.
nesemu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesemu.dir/build.make CMakeFiles/nesemu.dir/build
.PHONY : nesemu/fast

#=============================================================================
# Target rules for targets named sandbox

# Build rule for target.
sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sandbox
.PHONY : sandbox

# fast build rule for target.
sandbox/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/build
.PHONY : sandbox/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f external/spdlog/CMakeFiles/spdlog.dir/build.make external/spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

nes-emulator/main.o: nes-emulator/main.cpp.o
.PHONY : nes-emulator/main.o

# target to build an object file
nes-emulator/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesemu.dir/build.make CMakeFiles/nesemu.dir/nes-emulator/main.cpp.o
.PHONY : nes-emulator/main.cpp.o

nes-emulator/main.i: nes-emulator/main.cpp.i
.PHONY : nes-emulator/main.i

# target to preprocess a source file
nes-emulator/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesemu.dir/build.make CMakeFiles/nesemu.dir/nes-emulator/main.cpp.i
.PHONY : nes-emulator/main.cpp.i

nes-emulator/main.s: nes-emulator/main.cpp.s
.PHONY : nes-emulator/main.s

# target to generate assembly for a file
nes-emulator/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesemu.dir/build.make CMakeFiles/nesemu.dir/nes-emulator/main.cpp.s
.PHONY : nes-emulator/main.cpp.s

nes-emulator/sandbox.o: nes-emulator/sandbox.cpp.o
.PHONY : nes-emulator/sandbox.o

# target to build an object file
nes-emulator/sandbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/nes-emulator/sandbox.cpp.o
.PHONY : nes-emulator/sandbox.cpp.o

nes-emulator/sandbox.i: nes-emulator/sandbox.cpp.i
.PHONY : nes-emulator/sandbox.i

# target to preprocess a source file
nes-emulator/sandbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/nes-emulator/sandbox.cpp.i
.PHONY : nes-emulator/sandbox.cpp.i

nes-emulator/sandbox.s: nes-emulator/sandbox.cpp.s
.PHONY : nes-emulator/sandbox.s

# target to generate assembly for a file
nes-emulator/sandbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/nes-emulator/sandbox.cpp.s
.PHONY : nes-emulator/sandbox.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nesemu"
	@echo "... sandbox"
	@echo "... spdlog"
	@echo "... nes-emulator/main.o"
	@echo "... nes-emulator/main.i"
	@echo "... nes-emulator/main.s"
	@echo "... nes-emulator/sandbox.o"
	@echo "... nes-emulator/sandbox.i"
	@echo "... nes-emulator/sandbox.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

